# Generated by Django 4.1.5 on 2023-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('coursefees', models.IntegerField()),
                ('courseduration', models.CharField(max_length=100)),
                ('coursetextbox', models.TextField()),
            ],
        ),
    ]
