# Generated by Django 4.1.5 on 2023-02-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=300)),
                ('teacheremail', models.CharField(max_length=200)),
                ('teachermobile', models.IntegerField()),
                ('joindate', models.DateField()),
                ('education', models.CharField(max_length=200)),
                ('workexp', models.CharField(max_length=200)),
                ('ctc', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='due_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='saddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='scollege',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='sdegree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='semail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='smobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addstudents',
            name='sname',
            field=models.CharField(max_length=100),
        ),
    ]
