# Generated by Django 4.1.5 on 2023-02-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher_alter_addstudents_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
